/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fiestaSystem.ui;
import fiestaSystem.AppState;
import javax.swing.JOptionPane;

/**
 *
 * @author eevee
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    
    
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        card = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subLabel = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        roleLabel = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        adminBtn = new javax.swing.JButton();
        agentBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        footer = new javax.swing.JLabel();
        topBar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setPreferredSize(new java.awt.Dimension(520, 420));
        setResizable(false);

        centerPanel.setBackground(new java.awt.Color(240, 240, 240));
        centerPanel.setPreferredSize(new java.awt.Dimension(520, 420));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), javax.swing.BorderFactory.createEmptyBorder(16, 24, 16, 24)));
        card.setMaximumSize(new java.awt.Dimension(460, 240));
        card.setPreferredSize(new java.awt.Dimension(460, 240));
        card.setLayout(new javax.swing.BoxLayout(card, javax.swing.BoxLayout.Y_AXIS));

        titleLabel.setFont(new java.awt.Font("Courier New", 1, 32)); // NOI18N
        titleLabel.setText("FIESTA HOMES");
        titleLabel.setAlignmentX(0.5F);
        titleLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3)));
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleLabel.setOpaque(true);
        card.add(titleLabel);

        subLabel.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        subLabel.setForeground(new java.awt.Color(130, 130, 130));
        subLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subLabel.setText("REAL ESTATE MANGEMENT SYSTEM");
        subLabel.setAlignmentX(0.5F);
        subLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        card.add(subLabel);

        sep.setForeground(new java.awt.Color(200, 200, 200));
        card.add(sep);

        roleLabel.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(70, 70, 70));
        roleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roleLabel.setText("SELECT YOUR ROLE");
        roleLabel.setAlignmentX(0.5F);
        roleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 10, 1));
        card.add(roleLabel);

        btnPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel.setMaximumSize(new java.awt.Dimension(380, 90));
        btnPanel.setPreferredSize(new java.awt.Dimension(380, 90));
        btnPanel.setLayout(new java.awt.GridLayout(1, 3, 12, 0));

        adminBtn.setBackground(new java.awt.Color(0, 0, 0));
        adminBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        adminBtn.setForeground(new java.awt.Color(0, 230, 118));
        adminBtn.setText("ADMIN");
        adminBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        adminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminBtn.setFocusPainted(false);
        adminBtn.setMaximumSize(new java.awt.Dimension(120, 70));
        adminBtn.setOpaque(true);
        adminBtn.setPreferredSize(new java.awt.Dimension(120, 70));
        adminBtn.addActionListener(this::adminBtnActionPerformed);
        btnPanel.add(adminBtn);

        agentBtn.setBackground(new java.awt.Color(37, 99, 235));
        agentBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        agentBtn.setForeground(new java.awt.Color(255, 255, 255));
        agentBtn.setText("AGENT");
        agentBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        agentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agentBtn.setFocusPainted(false);
        agentBtn.setMaximumSize(new java.awt.Dimension(120, 70));
        agentBtn.setOpaque(true);
        agentBtn.setPreferredSize(new java.awt.Dimension(120, 70));
        agentBtn.addActionListener(this::agentBtnActionPerformed);
        btnPanel.add(agentBtn);

        customerBtn.setBackground(new java.awt.Color(255, 110, 199));
        customerBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        customerBtn.setText("CUSTOMER");
        customerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        customerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerBtn.setFocusPainted(false);
        customerBtn.setMaximumSize(new java.awt.Dimension(120, 70));
        customerBtn.setOpaque(true);
        customerBtn.setPreferredSize(new java.awt.Dimension(120, 70));
        customerBtn.addActionListener(this::customerBtnActionPerformed);
        btnPanel.add(customerBtn);

        card.add(btnPanel);

        footer.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        footer.setForeground(new java.awt.Color(180, 180, 180));
        footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer.setText("FIESTA COMMUNITIES — MEXICO, PAMPANGA");
        footer.setAlignmentX(0.5F);
        footer.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        card.add(footer);

        centerPanel.add(card, new java.awt.GridBagConstraints());

        topBar.setBackground(new java.awt.Color(0, 0, 0));
        topBar.setPreferredSize(new java.awt.Dimension(0, 5));
        topBar.setRequestFocusEnabled(false);

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerPanel.add(topBar, new java.awt.GridBagConstraints());

        getContentPane().add(centerPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        AppState.admin.login();
        new AdminFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_adminBtnActionPerformed

    private void agentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentBtnActionPerformed
        AppState.agent.login();
        new AgentFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_agentBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
    String name = JOptionPane.showInputDialog(
        this, "Enter your name:", "Customer Login", JOptionPane.PLAIN_MESSAGE);
    
        if (name == null || name.trim().isEmpty()) 
            return;
        
    AppState.currentCustomer = new fiestaSystem.users.Customer(
        "C-" + System.currentTimeMillis(), name.trim());
        
    AppState.currentCustomer.login();
    new CustomerMapFrame().setVisible(true);
    dispose();
    }//GEN-LAST:event_customerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton agentBtn;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel card;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton customerBtn;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JSeparator sep;
    private javax.swing.JLabel subLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topBar;
    // End of variables declaration//GEN-END:variables
}
